### ISSUE TITLE
Facade browser error in Ionic 3.1.1

### ISSUE THREAD

**Issue by biranchi2018** [morganster/ionic-youtube-ng2#1]
Runtime Error
Cannot find module "@angular/platform-browser/src/facade/browser".

Ionic info:
Ionic Framework: 3.1.1
Ionic App Scripts: 1.3.0
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 7.10.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by morganster** [comment]
hello, this project at first was intended to work with ionic 2, and it works with that version, that issue is because ionic 3 uses angular 4 and has many changes.

so i'm going to update the project to work with ionic 3, ng4.
