### ISSUE TITLE
Error when play video 

### ISSUE THREAD

**Issue by bodapratik** [morganster/ionic-youtube-ng2#2]
Runtime Error
this.youtube.player.loadVideoById is not a function

**Comment by morganster** [comment]
hello what are you settings, remember that this project is intended to run in ionic 3.

**Comment by enzonotario** [comment]
Hi @morganster I also have this problem.

If I execute ```console.debug('Youtube player', this.youtube.player);``` I get:
http://imgur.com/8gbC4dM

I'm using ionic 3.

Can you help me, please? And sorry for my english...

**Comment by morganster** [comment]
hello, did you change the view? i asking because the youtube player it seems that is not ready yet. this happens some times because there is no div for the player in the screen for example.

**Comment by enzonotario** [comment]
Sorry but what do you mean with "change the view" ? I don't understand you at all (because my poor english, maybe).

If I check the DOM, it has the youtube script tag. I understand that maybe it loads after, so I changed the `launchPlayer` method to:
```
launchPlayer(id): void {
  if (this.youtube.player && this.youtube.player.hasOwnProperty('loadVideoById')) {
    this.youtube.player.loadVideoById(id);
    this.youtube.videoId = id;
    return this.youtube;
  }
}
```

and I try to execute this in different times, but it doesn't work

**Comment by enzonotario** [comment]
Sorry! I just realize that you refers to:
```
<div id="player" class="embed-responsive embed-responsive-16by9">
        <div id="placeholder" style="width: 100%" class="embed-responsive-item"></div>
        <div class="embed-responsive-item" style="width: 100% ; z-index: 90;position: fixed; background-color: black; background: url('images/cover.png'); background-size:cover; " *ngIf="!onPlaying"></div>
    </div>
```
(https://github.com/morganster/ionic-youtube-ng2/blob/master/src/pages/home/home.html#L10)

Adding that, it works. But where is the `onPlaying` var? 
If I add that code, the player is always in the top (or where I added that code)...

**Comment by morganster** [comment]
sorry, that variable is not necessary, you can remove the *ngIf.
